### PR TITLE
Remove unknown/unhandled entities 🐛 

### PR DESCRIPTION
**Pull request by mahdiyazdani**
This PR removes the regular expression pattern for identifying and escaping unknown or unhandled entities for the `normalize_character_entities` method.

### CODE REVIEW

**Review by kuserich — APPROVED** [review]
Thank you, @mahdiyazdani . I have added a new function `normalize_xml_character_entities` that mimics the original function with the following differences:
- do not remove hex encoded entities
- remove the same named entities (although some would be valid)
- keep `&amp;` and do not replace with `&`

I did not add any additional named entities although I would be in favour of enabling support for other currency symbols such as `&yen;`. What do you think?

**Comment by mahdiyazdani** [comment]
Thank you @kuserich. Looks well structured 🙂  

> I did not add any additional named entities although I would be in favour of enabling support for other currency symbols such as &yen;. What do you think?

Enabling currency symbols would be a nice feature to have. However, I suspect that doing this would deviate from what originally WooCommerce displays in instances other than our block plugins.

**Comment by kuserich** [comment]
> Thank you @kuserich. Looks well structured 🙂
> 
> > I did not add any additional named entities although I would be in favour of enabling support for other currency symbols such as ¥. What do you think?
> 
> Enabling currency symbols would be a nice feature to have. However, I suspect that doing this would deviate from what originally WooCommerce displays in instances other than our block plugins.

It seems that WooCommerce does display the currency symbol in some cases. I assume that it displays the currency symbols in all places other than emails for currencies for which an HTML entity exists. However, I haven't tested this thoroughly yet and would propose testing/checking this and then adding additional currency symbols if WooCommerce supports these in non-email content too.

Screenshot 2021-11-11 at 22 04 45

**Comment by kuserich** [comment]
@mahdiyazdani In any case, I would propose adding additional HTML entities for other currencies in a second step outside this PR. If you agree, I would like to merge this PR and update our blocks. 🙂

**Comment by mahdiyazdani** [comment]
@kuserich Perhaps we can call the [get_woocommerce_currencies](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-core-functions.php) function from the WooCommerce core to render the configured currency for the shop with its symbol when available. What do you think?

**Comment by kuserich** [comment]
> @kuserich Perhaps we can call the [get_woocommerce_currency_symbols](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-core-functions.php#L662) function from the WooCommerce core to render the configured currency for the shop with its symbol when available. What do you think?

Thank you, @mahdiyazdani . Where would we call this function? I assume that the HTML content that we append in our WooCommerce blocks already contains these entities. If not, we could call this function. However, note that `get_woocommerce_currency_symbols` returns named entities that cause an error when used with XML (e.g. `&yen;` and `&pound;`). These would then require to be filtered akin to the initial proposal. Similarly, since we are normalizing the entire HTML string rather than only the currency symbol, we need to make sure that we're not accidentally also replacing non-currency content.

So, my proposal for is:
1. Extend `normalize_xml_character_entities` to replace other named entities like `&yen;` and `&fnof;` with their hex coded counterparts
2. Check if add-to-cart, products, and other WooCommerce blocks already retrieve currency symbols. If not, extend these blocks with `get_woocommerce_currency_symbols`, but only call it on the currency content.

What do you think?

**Comment by mahdiyazdani** [comment]
> Extend normalize_xml_character_entities to replace other named entities like &yen; and &fnof; with their hex coded counterparts

@kuserich I would be in favor of this approach instead 👍 Would you want me to compile a list of already supported currency symbols according to the WooCommerce function?

**Comment by kuserich** [comment]
> > Extend normalize_xml_character_entities to replace other named entities like ¥ and ƒ with their hex coded counterparts
> 
> @kuserich I would be in favor of this approach instead 👍 Would you want me to compile a list of already supported currency symbols according to the WooCommerce function?

I have added the currency symbols from [get_woocommerce_currency_symbols](https://github.com/woocommerce/woocommerce/blob/trunk/plugins/woocommerce/includes/wc-core-functions.php#L662) and extended the function with two generic named entities `&cent;` and `&curren;` from [the following list of HTML Currency Symbols](https://www.toptal.com/designers/htmlarrows/currency/). I believe this should be sufficient. What do you think?

**Comment by mahdiyazdani** [comment]
> I have added the currency symbols from get_woocommerce_currency_symbols and extended the function with two generic named entities &cent; and &curren; from the following list of HTML Currency Symbols. I believe this should be sufficient. What do you think?

Great. Thank you!

**Pull request merged**
